language: node_js
node_js:
  - 10
install:
  - npm i -g npm@6
  - npm ci
# cache:
#   directories:
#     - "$HOME/.npm"
before_deploy:
  - npm run build
deploy:
  repo: rebassjs/rebassjs.github.io
  provider: pages
  skip-cleanup: true
  verbose: true
  github-token: $GH_TOKEN
  target-branch: master
  local-dir: dist
  on:
    branch: src
